import Head from "next/head";
import { Inter } from "next/font/google";
import Slider from "@/component/Slider";
import Movies from "@/component/ContentHome";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mt-5 p-3">
          <Slider />
          <Movies/>
        </div>
      </main>
    </>
  );
}
